# Simple docker-compose for Phase 5B (Development)
version: '3.8'

services:
  # Voice AI Backend
  backend:
    build: .
    container_name: voice_ai_backend
    environment:
      # API Keys (set in .env file)
      - GROQ_API_KEY=${GROQ_API_KEY:-your_groq_key_here}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_key_here}
      - ADMIN_KEY=${ADMIN_KEY:-admin123}
      
      # Simple SQLite database (no external DB needed)
      - DATABASE_URL=sqlite:///./voice_ai.db
      
      # Mode Configuration
      - LOCAL_MODE=${LOCAL_MODE:-false}
      - ENABLE_MULTIPARTY=${ENABLE_MULTIPARTY:-true}
      - ENABLE_PERSISTENT_MEMORY=${ENABLE_PERSISTENT_MEMORY:-true}
      
      # Application Settings
      - MAX_SPEAKERS=${MAX_SPEAKERS:-4}
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - ./voice_ai.db:/app/voice_ai.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
